language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install --global expo-cli
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - mkdir project
        - cd project
        - npm install
        - npm install -g @aws-amplify/cli
        - amplify init -y --app https://github.com/willsmckenna/whatsfordinner.git
        - amplify push
        - amplify publish -y
        #- npm ci
        #- npx expo login -u wmckenn1 -p $EXPO_CLI_PASSWORD
        #- npx expo publish --non-interactive
