language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install --global expo-cli
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - mkdir project
        - cd project
        - npm install
        - npm install -g @aws-amplify/cli
        - amplify init \
          --app https://github.com/willsmckenna/whatsfordinner.git \
          --amplify "{\
          \"projectName\":\"whatsfordinner\"\
          \"envName\":\"dev\",\
          \”defaultEditor\”:\”code\”\
          \}"\
          --providers "{\
          \"useProfile\":false,\
          \"accessKeyId\":$AWS_ACCESS_KEY_ID,\
          \"secretAccessKey\":$AWS_ACCESS_KEY,\
          \"region\":\"us-east-1\" \
          \}"\
          --yes
        - amplify push
        - amplify publish -yes
        #- npm ci
        #- npx expo login -u wmckenn1 -p $EXPO_CLI_PASSWORD
        #- npx expo publish --non-interactive
